version: "3"
services:

  rstudio:
    image: rstudio_neonatal_dfc:latest
    build:
      context: ./rstudio
    ports:
      - "8787:8787"
    volumes:
          - "~/.ssh:/home/me/.ssh"
          - ".:/home/me/neonatal_dfc"
          - "./src:/home/me/neonatal_dfc/src"
          - "./data:/home/me/neonatal_dfc/data"
          - "./report:/home/me/neonatal_dfc/report"
    environment:
          - PASSWORD=letmein
