version: "3"
services:

  rstudio:
    image: rstudio_neonatal_dfc:latest
    build:
      context: ./rstudio
    ports:
      - "8788:8787"
    volumes:
          - "~/.ssh:/home/rstudio/.ssh"
          - ".:/home/rstudio/neonatal_dfc"
          - "./src:/home/rstudio/neonatal_dfc/src"
          - "./data:/home/rstudio/neonatal_dfc/data"
          - "./report:/home/rstudio/neonatal_dfc/report"
    environment:
          - PASSWORD=letmein
          - ROOT=true
          - USERID=1001
          - GROUPID=1001
