version: "3"
services:

  rstudio:
    image: rstudio_bstates:latest
    build:
      context: ./rstudio
    ports:
      - "8787:8787"
    volumes:
          - "~/.ssh:/home/me/.ssh"
          - ".:/home/me/brainStates"
          - "./src:/home/me/brainStates/src"
          - "./data:/home/me/brainStates/data"
          - "./report:/home/me/brainStates/report"
    environment:
          - USER=me
          - PASSWORD=letmein
          - GIT_USER="lucasfr"
          - GIT_EMAIL="lucas.franca@kcl.ac.uk"
